### ISSUE TITLE
Camera fails to open

### ISSUE THREAD

**Issue by Dilloo** [Descendant/rom_status#10]
It says occupied by other application

**Comment by Dil3mm4** [comment]
Even if the bug is reported poorly, I'll work on that since I may have a clue on my own on what's happening.

**Comment by Dil3mm4** [comment]
Should be solved by this commit on next release.
Feel free to re-open the issue if it's not fixed on OneDotFour.

https://github.com/Dil3mm4/treble_patches/commit/715ee16127a54e2b9f92aee4c1931a9e31f09971
