### ISSUE TITLE
Glitch Descendant - ver OneDotFive at Asus Zenfone Live L1 (ZA550KL) 

### ISSUE THREAD

**Issue by samsu-mbilung** [Descendant/rom_status#13]
**Bug**
Grapich glitch all over screen and very laggy

**To Reproduce**
Start on gapps wizard, and keep glitchy. 

![screenshot_20181120-221242_settings](https://user-images.githubusercontent.com/5321966/48783254-861c5c80-ed12-11e8-98bf-8b9c527bd553.png)

**Fix**
Adding line at build prop "debug.hwui.renderer=opengl" 

**Smartphone (please complete the following information):**
 - Device: ASUS Zenfone Live L1 (ZA550KL)
 - Descendant Version: OneDotFive
 - Treble support type: OEM
 - Gapps: Yes (open gapps micro)

**Comment by Dil3mm4** [comment]
Thanks for your report, this issue will be fixed in the upcoming release.

**Comment by samsu-mbilung** [comment]
update issue, screenshot of glitch issue.

**Comment by Dil3mm4** [comment]
Issues affect Moto E5 as well, solved by the same prop.

**Comment by samsu-mbilung** [comment]
Hope there are some kind switcher between hwui renderer (opengl/skiagl) at developer option on next release. Thx.

**Comment by Dil3mm4** [comment]
Fixed by https://github.com/Dil3mm4/device_phh_treble/commit/414dd2b96e73d8a52f5aa4b2420b87c862afa0cb
