### ISSUE TITLE
QS stay expanded

### ISSUE THREAD

**Issue by penn5** [Descendant/rom_status#15]
**Describe the bug**
QS don't unexpand even when closing and reopening the notification bar. The qs expanding at all may be a bug, I'll file a separate issue.

**To Reproduce**
Open notification bar
Don't open quick settings
Long-press something, I tested with Bluetooth.
It expands and when the nav bar is closed then opened again, it stays expanded.

**Expected behavior**
It doesn't stay expanded, or it doesn't expand in the first place.

1.5 Huawei treble without magisk and with bitgapps

Logcat not applicable

**Comment by Dil3mm4** [comment]
I've actually tried to reproduce that over TwoDotZero staging branch, and it doesn't seem to happen anymore. 
Please, reopen this issue if you'll have problems on the upcoming release. 

Thanks.
