### ISSUE TITLE
SystemUI doesn't work

### ISSUE THREAD

**Issue by penn5** [Descendant/rom_status#16]
**Describe the bug**
OneDotFive does not boot. After completing the bootanimation a black screen is shown. Long-pressing the power button shows the power menu, this is all I was able to do. It is fixed by dirty-flashing OneDotFive over OneDotFour.

**To Reproduce**
Install OneDotFive without SetupWizard (gapps irrelevant except setupwizard) and clean data. Tested on Honor 9 Lite hi6250

**Expected behavior**
The first boot succeeds and the LockScreen/Launcher shows

**Screenshots**
A black screen is shown.

**Smartphone:**
 - Device: hi6250
 - Descendant Version: OneDotFive only
 - Treble support type: OEM
 - Gapps: Without setupwiz, or none

**Comment by Dil3mm4** [comment]
A bad array was influencing theming settings on certain devices. 
As of now the problem is solved on our staging branch. 

Thanks for the report.
