### ISSUE TITLE
AnExplorer File Manager causing havoc with SD Card permissions

### ISSUE THREAD

**Issue by Dinkec27** [Descendant/rom_status#3]
With AnExplorer once you need to grant access to SD card it won't actually work,you will be able to select it but it won't do anything.
I have solved my issue by putting the stock Files app back and I suggest that you put it back or find a replacement if you can.

**Comment by Dil3mm4** [comment]
#1

**Comment by dinoderda** [comment]
i left an edit,forgot to mention something important,please read.
