### ISSUE TITLE
brightness slider not correctly displayed

### ISSUE THREAD

**Issue by vincentvidal** [Descendant/rom_status#6]
**Describe the bug**
The button on the brightness slider is not correctly displayed after changing QS shapes (I am not completely sure that it was correctly displayed before changing QS shapes though).

**Edit (1) :**
There is a conflict with an overlay for automatic brightness I added in /vendor/overalys. The bug only occurs only when automatic brigthness is activated (and changing QS shapes I can confirm). To get a correct display and changing QS shapes, I can disable automatic brighntess, change shape, activate again automatic brightness, and everything works well.

**Edit (2) :**
The same bug occurs when changing accent color instead of QS shapes.

**To Reproduce**
1. Change QS shape (Settings -> Display -> Advanced -> QS customization
2. Select one e.g. Circle
3. Scroll completely down notification panel to make brightness slider appear

**Screenshots**
![screenshot_20181016-100819](https://user-images.githubusercontent.com/24563559/47002088-53d47980-d12c-11e8-89bb-efd3bd253354.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi MI8 SE
 - Descendant Version: OneDotThree
 - Treble support type: OEM
 - Gapps: Yes

**Comment by Dil3mm4** [comment]
I'm sorry but I can't reproduce the issue. 
If I have to give out a rough bet that's on your overlay that is messing something more than only Automatic brightness.
Here's the same setup you showed in the pic.
Anyway I did appreciate the detail of the bug report. 

![photo_2018-10-16_16-37-44](https://user-images.githubusercontent.com/21145257/47024383-d88dba80-d161-11e8-9832-c27a723bc3ec.jpg)

**Comment by Dil3mm4** [comment]
Discovered what's up, not your overlay fault. 
Seems adaptive brightness kicks in and changes the color. 
I will investigate further.

**Comment by vincentvidal** [comment]
Ok great... At least for me, not you ;-)

**Comment by Dil3mm4** [comment]
> At least for me, not you ;-)

You can say that outta loud LMAO.

**Comment by Dil3mm4** [comment]
Coloring should be solved in OneDotFive release.
