### ISSUE TITLE
"deep sleep" state never triggered in always on display mode

### ISSUE THREAD

**Issue by vincentvidal** [Descendant/rom_status#8]
**Describe the bug**
The device never enters "deep sleep" state when AOD is activated, which yields a severe battery drain. For example, my devices loses 30% overnight, while only 3% without AOD. This did not happen with MIUI 10 and AOD, the battery drain overnight was around 8%, and the device was really entering "deep sleep" state as confirmed by a monitoring app.

**To Reproduce**
1. Go to 'Settings -> Display -> Advanced -> Ambient display'
2. Check 'Always on'
3. Install a monitoring app like BetterBatteryStats
4. Create a custom reference, switch off device immedately
5. Wait for several minutes, switch on the device
6. Observe statistics for the custom reference

**Expected behavior**
The "deep sleep" state should be triggered and the battery drain should be much lower.

**Screenshots**
BetterBatteryStats summary statistics for several minutes while screen off all the time:
![screenshot_20181016-111816](https://user-images.githubusercontent.com/24563559/47006098-728b3e00-d135-11e8-8abd-96a2c2abd3de.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi MI8 SE
 - Descendant Version: OneDotThree
 - Treble support type: OEM
 - Gapps: Yes

**Comment by Dil3mm4** [comment]
I dunno anything about this LCD panel, nor if that's supposed to be a OLED.
But other than the screenshot of the usage, I need logs this time.

**Comment by vincentvidal** [comment]
The screen is an AMOLED one, so the battery drain should be (and is with MIUI) relatively low. The big difference being that the "deep sleep" state is never entered with Descendant.
What kind of logs do you need? Could you please help me to generate the most useful data for you?

**Comment by Dil3mm4** [comment]
`adb logcat -b all `

will suffice

**Comment by vincentvidal** [comment]
Here is a smaller logcat that I hope easier to inspect:

- at start, AOD is on.
- at 20:20:00.637: key press off
- at 20:30.00.846: key press on, AOD set to off
- at 20:31:00.702: key press off
- at 20:40:06.031: key press on, device awakes

As can be seen in the logs,  things like device_idle_off only happen in the second phase between 20:31 and 20:40, when AOD is disabled. Furthermore, there are long periods of complete inactivity, e.g. between 20:36 and 20:39, which does not happen between 20:20 and 20:30.

[logcat.zip](https://github.com/Descendant/bug_tracker/files/2484669/logcat.zip)

**Comment by Dil3mm4** [comment]
This is something for @phhusson. 
I will forward that to him.

**Comment by vincentvidal** [comment]
Ok thanks.

**Comment by phhusson** [comment]
@Dil3mm4 do you have framework-res's config_powerDecoupleAutoSuspendModeFromDisplay to true?

**Comment by Dil3mm4** [comment]
@phhusson that's supposedly overlays job to tell me if it's needed or not (as we did per Huawei devices, am I wrong?)

The default it's set to false, as I dunno if some legacy devices treble enabled could experience come battery drain by that bool on true.

**Comment by vincentvidal** [comment]
This is related with https://github.com/phhusson/treble_experimentations/issues/148, the overlay has never been submitted. I got the latest framework-res.apk from china dev miui 10 and now have an overlay that works pretty well. It adds auto brightness and AOD. I could PR it after a few more testing.
However there is still the problem related in https://github.com/phhusson/vendor_hardware_overlay/pull/31: @phhusson you mean that an overlay of SystemUI should be added, in order to set the property doze_display_state_supported? Is there a way to set this property in the hardware-overlay for mi8se?

**Comment by vincentvidal** [comment]
In fact the overlay was commited in the branch 'master' and not in 'pie', which is the branch synced by local_manifests.. The problem of setting doze_display_state_supported remains I think.

**Comment by Dil3mm4** [comment]
PR your overlay to https://github.com/Dil3mm4/vendor_hardware_overlay

**Comment by Dil3mm4** [comment]
Two months have gone by, I consider this issue fixed. 
In case it isn't, please, feel free to re-open.
