### ISSUE TITLE
Dark mode notification text it's hard too see

### ISSUE THREAD

**Issue by ghost** [Descendant/rom_status#9]
**Describe the bug**
Black font on dark theme notifications, hard to see.

**To Reproduce**
1-Enable dark mode in display.

**Expected behavior**
Text should be white, but its black, and hard too see the text.

**Screenshots**
![photo_2018-10-18_22-16-49](https://user-images.githubusercontent.com/40524456/47181887-6fa27000-d324-11e8-923c-bce8978e9887.jpg)

**Smartphone (please complete the following information):**
 - Device: PRA-LX1
 - Descendant Version: OneDotThree
 - Treble support type: OEM
 - Gapps: BitGapps

**Full bugreport/trimmed logcat**
Not nedded.

**Comment by Dil3mm4** [comment]
Thanks for the report, I'll look at it.

**Comment by Dil3mm4** [comment]
Should be solved by:

https://github.com/Descendant/frameworks_base/commit/d635e865583a379f56dc06d7e8548641108a38a1
https://github.com/Descendant/vendor_descendant/commit/fe4cf5cba424416d0354df58bc75fd1b1aedf4ce

on OneDotFour

**Comment by ghost** [comment]
The problem persist in onedotfour.
